import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Uci Dashboard || Digital-Sync Tecnologeis Service Pvt Ltd.",
  description: "Generated by Digital-Sync - Sagar Sharma",
};
